### Get all products in the collection
GET http://localhost:5000/api-docs/#/Inventory/get_api_inventory
Content-Type: application/json

### Get single product by _id
GET http://localhost:5000/api-docs/#/Inventory/get_api_inventory__id_/68c724d7472ee9e809a9aa84
Content-Type: application/json

