### Get all contacts
GET https://product-inventory-api-85ge.onrender.com/api-docs/#/Inventory/get_api_inventory
Content-Type: application/json

###

### Get single contact by _id
GET https://product-inventory-api-85ge.onrender.com/api-docs/#/Inventory/get_api_inventory/68c724d7472ee9e809a9aa83
Content-Type: application/json

###

### Update a contact (replace with real _id) you must login
PUT https://product-inventory-api-85ge.onrender.com/api-docs/#/Inventory/get_api_inventory/68c724d7472ee9e809a9aa83
Content-Type: application/json


###

### Delete a contact (replace with real _id) you must login
DELETE https://product-inventory-api-85ge.onrender.com/api-docs/#/Inventory/get_api_inventory/68c724d7472ee9e809a9aa83
Content-Type: application/json

